name: 'Bump Version'

on:
  push:
    branches:
      - 'develop'

jobs:
  bump-version:
    name: 'Bump Version on develop'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: 18
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
